### ISSUE TITLE
Difference in calibration cost between ROS and ROS 2. Has the solver method changed?

### ISSUE THREAD

**Issue by Tacha-S** [mikeferguson/robot_calibration#192]
I am performing calibration using `wall_plane_finder` and `scan_plane_finder`. In ROS, I was able to achieve calibration with a cost on the order of 10^-4, but in ROS 2, it stops at around 10^-1.  

Are there any specific points to be aware of when migrating?  

I suspect issues related to the sensor driver or DDS (since the camera point cloud had significant latency unless I used Cyclone DDS). If you have any insights on potential causes, I would appreciate your input.

ROS params:

capture
```yaml
features:
  wall_plane_finder:
    type: robot_calibration/PlaneFinder
    topic: /head_camera/depth_registered/points
    transform_frame: base_link
    camera_info_topic: /head_camera/depth/camera_info
    camera_driver: /head_camera/driver
    camera_sensor_name: head_camera_wall
    min_x: 0.0
    max_x: 1.5
    min_y: -2.0
    max_y: 2.0
    min_z: 0.3
    max_z: 3.0
    ransac_points: 1000
    points_max: 1000
  scan_plane_finder:
    type: robot_calibration/ScanFinder
    topic: /laser/scan_filtered
    transform_frame: base_link
    sensor_name: laser
    min_x: 0.0
    max_x: 1.5
    min_y: -2.0
    max_y: 2.0
    ransac_points: 1000
    points_max: 1000
```

calibrate
```yaml
base_link: base_link
models:
  - name: head_camera_wall
    type: camera3d
    frame: head_camera_rgb_optical_frame
  - name: laser
    type: chain
    frame: laser_link
free_params:
  - head_pan_joint
  - head_tilt_joint
error_blocks:
  - name: wall_plane
    type: plane_to_plane
    model_a: head_camera_wall
    model_b: laser
    scale_normal: 1.0
    scale_offset: 0.0
```

ROS 2:

capture
```yaml
chains:
      - head
    head:
      topic: head_trajectory_controller/follow_joint_trajectory
      joints:
        - head_pan_joint
        - head_tilt_joint
    duration: 2.0
    features:
      - wall_plane_finder
      - scan_plane_finder
    wall_plane_finder:
      type: robot_calibration::PlaneFinder
      topic: /head_camera/depth_registered/points
      transform_frame: base_link
      camera_info_topic: /head_camera/depth/camera_info
      camera_driver: /head_camera/driver
      camera_sensor_name: head_camera_wall
      min_x: 0.0
      max_x: 1.5
      min_y: -2.0
      max_y: 2.0
      min_z: 0.3
      max_z: 3.0
      ransac_points: 1000
      points_max: 1000
    scan_plane_finder:
      type: robot_calibration::ScanFinder
      topic: /laser/scan_filtered
      transform_frame: base_link
      sensor_name: laser
      min_x: 0.0
      max_x: 1.5
      min_y: -2.0
      max_y: 2.0
      ransac_points: 1000
      points_max: 1000
```

calibrate
```yaml
base_link: base_link
    calibration_steps:
      - single_calibration_step
    single_calibration_step:
      models:
        - head_camera_wall
        - laser
      head_camera_wall:
        type: camera3d
        frame: head_camera_rgb_optical_frame
      laser:
        type: chain3d
        frame: laser_link
      free_params:
        - head_pan_joint
        - head_tilt_joint
      error_blocks:
        - wall_plane
      wall_plane:
        type: plane_to_plane
        model_a: head_camera_wall
        model_b: laser
        scale_normal: 1.0
        scale_offset: 0.0
```
